- defaults:
    create: true
    relink: true
- link:
   ~/.bashrc: shells/bash/bashrc
   ~/.bash_profile: shells/bash/profile
   ~/.bash_aliases: shells/bash/aliases
   ~/.bash_prompt:  shells/bash/prompt
   ~/.bash_completion: shells/bash/bash_completion
- link:
   ~/.local/bin/:
    path: shells/bash/bin/*
    relink: true
    create: true
    glob: true
