- defaults:
    create: true
    relink: true
- link:
    ~/.config/fish/config.fish: shells/fish/config.fish
    ~/.config/fish/fish_plugins: shells/fish/fish_plugins
    ~/.config/fish/conf.d/:
      path: shells/fish/conf.d/*
      relink: true
      create: true
      glob: true
    # Install fisher
    ~/.config/fish/functions/fisher.fish:
      path: ./shells/fish/functions/fisher.fish
      relink: true
      create: true
- shell:
    - command: 'fish --command="fisher update"'
- link:
    # Install / Reinstall functions
    ~/.config/fish/functions/:
      path: shells/fish/functions/*
      relink: true
      create: true
      glob: true
      force: true
