- create: [~/.local/]
- shell: 
  - command: bash tools/googler/install.sh
    description: installing googler
    stdout: true
- link:
   ~/.config/dotfiles/run.d/:
    glob: true
    path: tools/googler/googler/auto-completion/bash/*
    relink: true
    create: true
   ~/.config/dotfiles/run.d/:
    glob: true
    path: tools/googler/googler/auto-completion/googler_at/*
    relink: true
    create: true
