- link:
   ~/.config/dotfiles/run.d/:
    glob: true
    path: envs/hpc/run.d/*
    relink: true
    create: true
- link:
   ~/.local/bin/:
    glob: true
    path: envs/hpc/usr/local/bin/*
    relink: true
    create: true
- link:
   ~/usr/local/bin/vd:
    path: envs/hpc/visidata_hpc/bin/vd
    relink: true
    create: true
