- clean:
  - '~/.config/kitty/'
- link:
   ~/.config/kitty/kitty.conf:
     path: apps/kitty/kitty.conf
     relink: true
     create: true
   ~/.config/kitty/conf.d:
     path: apps/kitty/conf.d
     relink: true
     create: true
   ~/.config/kitty/sessions:
     path: apps/kitty/sessions
     relink: true
     create: true
