- shell:
  - command: 'bash tools/linuxbrew/install_linuxbrew'
    stdout: true
    quiet: false
    description: Install linuxbrew via online script.
- link:
   ~/.config/dotfiles/run.d/linuxbrew:
    path: tools/linuxbrew/run.d/linuxbrew
    relink: true
    create: true
