- clean:
  - '~/.ssh/config.d'
- link:
   ~/.config/dotfiles/run.d/:
    glob: true
    path: tools/ssh/run.d/*
    relink: true
    create: true
    # For shared configuration
   ~/.ssh/config.d/:
    glob: true
    path: tools/ssh/config.d/*
    relink: true
    create: true
    clean: true
    # Used to mount hpc file systems
   ~/.local/bin/:
    path: tools/ssh/bin/*
    glob: true
    create: true
    relink: true
- shell:
  - command: 'bash tools/ssh/add_include.sh'
    stdout: true
    quiet: false
    description: Add include statement to ssh config
  # For connection sharing
- shell:
  - command: 'bash install-private ssh'
    stderr: true
- create:
   - ~/.ssh/sockets

