- link:
   ~/.config/dotfiles/run.d/:
    glob: true
    path: envs/termux/run.d/*
    relink: true
    create: true
- shell:
  - command: bash envs/termux/install_utils.bash
    description: installing helpful utilities
