- link:
   ~/.tmux/plugins/tpm:
     create: true
     path: tmux/tpm
   ~/.tmux.conf: tmux/config/tmux.conf
   ~/.tmux/: 
    glob: true
    path: tmux/config/conf.d/*
    relink: true
    create: true
# - shell:
#   - command: ~/.tmux/plugins/tpm/bin/clean_plugins
#     description: Cleaning TPM plugins
#   - command: ~/.tmux/plugins/tpm/bin/install_plugins
#     description: Installing TPM plugins
- link:
   ~/.local/share/bash_completion.d/tmux:
    # glob: true
    path: tmux/completion/completions/tmux
    relink: true
    create: true
   ~/.config/dotfiles/run.d/:
    glob: true
    path: tmux/run.d/*
    relink: true
    create: true
