- clean:
  - '~/.config/wezterm/'
- link:
   ~/.config/wezterm/wezterm.lua:
     path: apps/wezterm/wezterm.lua
     relink: true
     create: true
   ~/.config/wezterm/conf_d/:
     path: apps/wezterm/conf_d/*
     relink: true
     create: true
     glob: true
   # ~/.config/kitty/sessions:
     # path: apps/kitty/sessions
     # relink: true
     # create: true
