#!/bin/sh

# ARGS:
# if the first argument is "no-bashrc":
#    does not source bashrc

# Description
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.

# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ "$1" != "no-recurse" ]; then
      if [ -f "$HOME/.bashrc" ]; then
       . "$HOME/.bashrc no-recurse"
      fi

      if [ -f "$HOME/.bash_profile" ]; then
       . "$HOME/.bash_profile no-recurse"
      fi
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
# set PATH to include another user bin
if [ -e ~/usr/local/bin ]; then
	export PATH="~/usr/local/bin:${PATH}"
fi

##########################################
# MANPATH handling
##########################################

# I used to use $(manpath -g) but that gave a 
# VERY verbose error on centos 6

if [ -d "$HOME/.local/share/man" ]; then
  export MANPATH="$HOME/.local/share/share/man:$(manpath)"
fi

if [ -d "$HOME/usr/local/share/man" ]; then
  export MANPATH="$HOME/usr/local/share/man:$(manpath)"
fi

export PATH="$HOME/.cargo/bin:$PATH"
