#!/usr/bin/env bash

test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
test -d /opt/homebrew/bin/ && eval $(/opt/homebrew/bin/brew shellenv)

if hash brew 2>/dev/null; then
  # Fuzzy Finder
  brew install fzf 
  # fast & featured path jumper
  brew install zoxide
  
  # fancier version of ls 
  brew install lsd
  # Really nice version of tree 
  brew install broot
  
  # Install recent tmux
  brew install --HEAD tmux
fi
