#!/usr/bin/env bash

if hash brew 2>/dev/null; then
  brew install \ 
    # fuzzyfinder
    fzf \
    # fast & featured path jumper
    zoxide \
    # fancier version of ls
    lsd \
    # Really nice version of tree
    broot
  
  # Install recent tmux
  brew install --HEAD tmux
fi
