#!/usr/bin/env bash

alias sshhosts="sed -rn ‘s/^\s*Host\s+(.*)\s*/\1/ip’ ~/.ssh/config"

function sshpeed {
  local TEST_SIZE=10485760 # 10 MB

  pv --size "$TEST_SIZE" --stop-at-size -pteba /dev/zero | ssh "$@" 'cat > /dev/null'
}
alias sshpeed='sshpeed'

function ssh_cancel_shared {
  local ssh_host=""
  local hosts=(jump jhpc vhpc)

  local mounted=(ACS STEMI)
  local mount_point=""
  local mount_path=""
  echo "Unmounting sshfs mounts:"

  for mount_point in ${mounted[@]}; do
    mount_path="$HOME/work/.project/${mount_point}"
    echo    " - $mount_path"
    echo -n "   - "
    fusermount -u "$mount_path"
  done

  echo "Checking shared connections:"

  for ssh_host in ${hosts[@]}; do
    echo    " - $ssh_host"
    echo -n "   - "
    ssh -O check $ssh_host && ssh -O exit $ssh_host && echo "   - exited $ssh_host"
  done
}

alias ssh_cancel_shared='ssh_cancel_shared'
