#!/usr/bin/env bash


which openconnect>/dev/null && which ocproxy>/dev/null || \
  echo "openconnect & ocproxy required"

# Don't use jump, because you're using the VPN
SSH_HOST="vhpc"

sshfs ${SSH_HOST}:/project/STEMI/ ~/work/.project/STEMI \
  -o IdentityFile=~/.ssh/id_rsa \
  -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3 \
 #-o allow_other #commentted out because I'm not root

sshfs ${SSH_HOST}:/project/ACS/ ~/work/.project/ACS \
  -o IdentityFile=~/.ssh/id_rsa \
  -o reconnect,ServerAliveInterval=15,ServerAliveCountMax=3 


ssh "$SSH_HOST"

echo "Finished ssh-ing"


bash
