#!/usr/bin/env bash
# Locates linuxbrew installation, and activates it

# Moved directly to bash profile
#test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
#test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

