# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"



# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
export GOPATH=${HOME}/go
export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin

[[ -e "/usr/local/etc/bash_completion.d/singularity" ]] && . "/usr/localal/etc/bash_completion.d/singularity"

#export PATH=/usr/jdk/bin:${PATH}

# Load uni credentials to environment
# Sets UNIKEY and UNIPASS

if [ -f ~/.uni_auth ]; then
    . ~/.uni_auth
fi

export CC=clang

if [ -f ~/.bash_prompt ]; then
  . ~/.bash_prompt
fi


# If fzf exists, use it
if [ -f ~/.fzf.bash ]; then
  source ~/.fzf.bash

  _FZF_EXISTS="fzf"
fi

# This will be changed if fzf exists && we can use z.lua
alias zf='z'

# IF zoxide exists, use it
# https://github.com/ajeetdsouza/zoxide
# zoxide is the slickest z implementation
# (and fastest) - implemented in rust
# But it's a bit less portable to old envs
# eg the hpc. I install it w/ linuxbrew
if hash zoxide 2>/dev/null; then
  eval "$(zoxide init bash)"
elif [ -e ~/.config/dotfiles/z.lua/z.lua ]; then
  # https://github.com/skywind3000/z.lua
  # z.lua is faster than z.sh, and more portable
  # than zoxide. 
  # It also integrates w/ fzf
  eval "$(lua ~/.config/dotfiles/z.lua/z.lua --init bash enhanced ${_FZF_EXISTS:-})"

  if [[ ! -z ${_FZF_EXISTS+x} ]]; then 
    alias zf='z -I'
  fi
elif [ -e ~/.config/dotfiles/z.sh/z.sh ]; then
  # z.sh is the most portable z implementation
  # That i've noticed (maybe z.lua is equal)
  . ~/.config/dotfiles/z.sh/z.sh
fi


#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/matty/.sdkman"
[[ -s "/home/matty/.sdkman/bin/sdkman-init.sh" ]] && source "/home/matty/.sdkman/bin/sdkman-init.sh"

