#!/bin/env bash
# ~/.bash_profile


# Just source the generic profile, and bashrc

test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)


if [ "$1" != "no-recurse" ]; then
  shell_confs=( ".bashrc" ".profile" )

  for i in "${shell_confs[@]}"
  do
    if [ -e "${HOME}/${i}" ]; then
     . "${HOME}/$i" "no-recurse"
    fi
  done
fi


# Run any executables found in .config/dotfiles/run.d
# This will allow for dynamic loading of certain profile components
# That may not be present for all profiles

run_d="$HOME/.config/dotfiles/run.d" 
if [ -d "${run_d}" ] ; then
  for f in ${run_d}/{.*,*} ; do
    if [[ \
      ( ! -z "${f}" ) && \
      "$f" != "${run_d}/." && \
      "$f" != "${run_d}/.." \
      ]]; then

      source "${f}"
    fi
  done
fi


export PATH="$HOME/.cargo/bin:$PATH"


[[ -f ~/.config/broot/launcher/bash/br  ]] && source /home/matty/.config/broot/launcher/bash/br

export PATH="$HOME/.poetry/bin:$PATH"
