#!/bin/env bash
# ~/.bash_profile

# Just source the generic profile, and bashrc

[[ -f ~/.profile ]] && . ~/.profile
[[ -f ~/.bashrc ]] && . ~/.bashrc


# Run any executables found in .config/dotfiles/run.d
# This will allow for dynamic loading of certain profile components
# That may not be present for all profiles

run_d="$HOME/.config/dotfiles/run.d" 
if [ -d "${run_d}" ] ; then
  for f in "$(ls "${run_d}")"; do
    if [[ ! -z "${f}" ]]; then
      source "${run_d}/${f}"
    fi
  done
fi

