#!/bin/env bash

alias lout='socat -d -d TCP4-LISTEN:8080,bind=10.0.2.15,fork TCP4:localhost:8080'

# "serve" quickly jumps to the correct dir and serves the website
function serve {
    pushd ~/public_html
    php -S localhost:8080
    popd
  }

alias serve='serve'

function db_url {
  echo "mysql://$DBUSER:$DBPASS@localhost:3306/cronnit"
}

function access_db {
  local args="${@:1}"
  mysql --user="$DBUSER" --password="$DBPASS" "$@"
}

alias explore_db='vd $(db_url)'

