
function Rproj_open {
  (xdg-open $(find . -maxdepth 1 -name "*.Rproj") > /dev/null 2>&1 &)
}

function gui_run {
  (xdg-open $1 > /dev/null 2>&1 &)
}

alias Rproj=Rproj_open
alias please=sudo
alias sshlog='tail -n 1000 /var/log/auth.log | grep -E ssh'

alias check_ssh='curl https://ifconfig.co/port/22'

alias pkginst="R CMD INSTALL --no-multiarch --with-keep.source ."
alias pull_deps="Rscript --no-save --no-restore -e 'renv::restore(confirm = FALSE)'"

alias sshpc='ssh -CXY mstr3336@hpc.sydney.edu.au'
alias mvim='qmv -f do'

alias colcat='highlight --out-format=xterm256'

function update_pkg {
  git pull
  pull_deps
  pkginst
}

