#!/bin/env bash

# From bash_bindings/linux/bash_aliases
# Check the distro
function check_distro {
  local unameOut="$(uname -s)"
  local machine="$unameOut"
  case "${unameOut}" in
      Linux*)     machine=Linux;;
      Darwin*)    machine=Mac;;
      CYGWIN*)    machine=Cygwin;;
      MINGW*)     machine=MinGw;;
      *)          machine="UNKNOWN:${unameOut}"
  esac

  echo ${machine}
}

distro="$(check_distro)"

# If you're running osx, use treat xdg-open as alias of open
if [[ "${distro}" == "Mac" ]]; then
  alias xdg-open='open'
fi


function gui_run {
  (xdg-open $1 > /dev/null 2>&1 &)
}

alias please=sudo


####################
# SSH Helpers
####################
# ssh server helpers

alias sshlog='tail -n 1000 /var/log/auth.log | grep -E ssh'
alias check_ssh='curl https://ifconfig.co/port/22'

# ssh client helpers

HOME_DOMAIN=mstrasiotto.hopto.org
alias sshpc='ssh -CXY mstr3336@hpc.sydney.edu.au'

function sshome {
  ssh -XYC matty@${HOME_DOMAIN}
}

function get_displays {
  (cd /tmp/.X11-unix && for x in X*; do echo ":${x#X}"; done)
}


######################
# R workflow helpers

function Rproj_open {
  (xdg-open $(find . -maxdepth 1 -name "*.Rproj") > /dev/null 2>&1 &)
}
alias Rproj=Rproj_open

alias pkginst="R CMD INSTALL --no-multiarch --with-keep.source ."
alias pull_deps="Rscript --no-save --no-restore -e 'renv::restore(confirm = FALSE)'"
alias test_pkg='Rscript --no-save --no-restore -e "devtools::test()"'


function update_pkg {
  git pull
  pull_deps
  pkginst
}


# General helpers

alias mvim='qmv -f do'

alias colcat='highlight --out-format=xterm256'


#############################
# Aliases From linux/bashrc


# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

function ascend_to_root {
  local top_level="$(pwd)"

  if top_level="$(git rev-parse --show-toplevel 2>/dev/null)" ; then
    cd "$top_level"
    return 0
  else 
    echo "not in a repo"
    return 1
  fi
}

if hash aws 1>&2 2>/dev/null ; then

  function aws_list_all {
    for region in `aws ec2 describe-regions --region us-east-1 --output text | cut -f4`
    do
      echo -e "\nListing Instances in region:'$region'..."
      aws ec2 describe-instances --region $region
    done
  }

  alias aws_ls='aws_list_all'

fi


alias here='ascend_to_root'

alias @alias='alias | fzf'

alias vncinit='vncserver -rfbport 6969'

###########################################
# ls
###########################################

# lsd (LSDeluxe) is a fancier ls

# https://github.com/Peltoche/lsd
if hash lsd 2>&1 >/dev/null; then
  alias ls='lsd'
  alias l='ls -l'
  alias la='ls --almost-all'
  alias lla='ls -l --almost-all'
  alias lt='ls --tree'
fi

function docker_bash_f {
  local container="$1" 
  shift
  local cmd

  if [ "$#" -eq "0" ]; then
    cmd="bash"
  else
    cmd="$1"
    shift

  fi

  sudo docker exec -it "$container" "$cmd" "$@"
}

alias docker_bash='docker_bash_f'

function git_migrate {
  if [[ $# -eq 0 ]]; then
    echo "usage: $FUNCNAME <url-to-reponame>" 1>&2
    echo "  <url-to-reponame> should include everything up to the name of this repo" 1>&2
    echo "     eg git@github.com:username"

    return 1
  fi

  local new_origin="$1"

  local reponame="$(basename $(git remote get-url origin) .git)"
  
  git fetch --prune
  
  git remote rename origin old-origin
  
  git remote add origin "${new_origin}/${reponame}"

  git push --prune origin +refs/remotes/old-origin/*:refs/heads/* +refs/tags/*:refs/tags/*
}

alias git2uni='git_migrate git@github.sydney.edu.au:speed-extract'

function table_sed {
  local pattern="$1"
  local n_extra_lines="${2:-0}"

  sed -n "1,+${n_extra_lines}p ; /.*${pattern}.*/p"
}

function docker_pgrep {
  local pattern="$1"
  sudo docker ps | table_sed "$pattern" "0"

}

function compose_pgrep {
  local pattern="$1"
  sudo docker-compose ps | table_sed "$pattern" "1"
}

alias pip='python -m pip'

function reauthor_all {
  local USAGE=$(cat << EOF
  Usage:
    ${FUNCNAME[0]} <email> [<upstream>]

  DESCRIPTION:

  For each commit between HEAD & <upstream> where the commit email matches
  <email>, reauthor the commit to the current settings for user.name & user.email

  OPTIONS:
    <email>
      Required.
      The invalid email address that should be replaced with the currently
      configured email

    <upstream>
      Optional.
      defaults to --root. The parent of the last commit to be reauthored.
      (<upstream> is used in the same sense as git rebase documentation uses it)
EOF
  )


  if [[ "$#" -eq 0 ]]; then
    echo "Incorrect usage, no email given, usage is: " 1>&2
    echo "$USAGE" 1>&2
    return 1
  fi

  local old_email="$1"
  local to_ref="${2:---root}"
  # SO: https://stackoverflow.com/a/34863275/9238801
  # git rebase -i HEAD~40 -x "git commit --amend --author 'Author Name <author.name@mail.com>' --no-edit"
  local new_email="$(git config --get user.email)"
  local new_name="$(git config --get user.name)"

  # https://stackoverflow.com/a/58635589/9238801
  # get each commit's email address
  local command='bash -c "'
  command+='[[ "$(git log -1 --pretty=format:'%ae')" ==' 
  command+=" '$old_email' ]] && git commit --amend --author '$new_name <$new_email>' --no-edit || true"
  command+='"'
  

  git rebase -i "${to_ref}" -x "$command"
}

alias git_reauthor_all='reauthor_all'

# this is now recommended practise
alias pip='python -m pip'



if hash scrcpy 1>&2 2>/dev/null ; then
  function _mirror_droid_connect {
    scrcpy --stay-awake --turn-screen-off 2>&1 >>~/.scrcpy.log 
  }

  function _mirror_droid_repeat {
    while :
    do
      adb wait-for-usb-device
      _mirror_droid_connect
      sleep 0.1
    done
  }

  function mirror_droid_repeat {
    _mirror_droid_repeat &
  }
  
fi

alias tty-share-own='tty-share -public -tty-proxy term.straz.to:3456'
